version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.browser
    networks:
      - local_browser_net
    ports:
      - "3000-3020:3000-3020"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "5000:5000" 
    depends_on:
      - app
    networks:
      - local_browser_net
    volumes:

      - ./configs/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/proxy/conf.d:/etc/nginx/conf.d:ro
      - ./share/nginx:/usr/share/nginx

    command: [nginx-debug, '-g', 'daemon off;']

networks:
  local_browser_net:
    driver: bridge
