FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    libgtk-3-0 \
    libx11-xcb1 \
    libasound2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m camoufox fetch

COPY server/ /app/server/

# EXPOSE 3000-4000

CMD ["python", "server/bootstrap.py"]

