version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.browser
    networks:
      - local_browser_net
    env_file:
      - .env
    # ports:
    #   - "3000-4000:3000-3020"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - local_browser_net
    volumes:

      - ./configs/proxy/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./configs/proxy/conf.d:/etc/nginx/conf.d:rw
      - ./share/nginx:/usr/share/nginx

    command: [nginx-debug, '-g', 'daemon off;']

networks:
  local_browser_net:
    driver: bridge
